# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xps/devel/backend

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xps/devel/backend

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"config\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xps/devel/backend/CMakeFiles /home/xps/devel/backend//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xps/devel/backend/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aeronautical_backend

# Build rule for target.
aeronautical_backend: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aeronautical_backend
.PHONY : aeronautical_backend

# fast build rule for target.
aeronautical_backend/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/build
.PHONY : aeronautical_backend/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

src/ConflictController.o: src/ConflictController.cpp.o
.PHONY : src/ConflictController.o

# target to build an object file
src/ConflictController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ConflictController.cpp.o
.PHONY : src/ConflictController.cpp.o

src/ConflictController.i: src/ConflictController.cpp.i
.PHONY : src/ConflictController.i

# target to preprocess a source file
src/ConflictController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ConflictController.cpp.i
.PHONY : src/ConflictController.cpp.i

src/ConflictController.s: src/ConflictController.cpp.s
.PHONY : src/ConflictController.s

# target to generate assembly for a file
src/ConflictController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ConflictController.cpp.s
.PHONY : src/ConflictController.cpp.s

src/ConflictRepository.o: src/ConflictRepository.cpp.o
.PHONY : src/ConflictRepository.o

# target to build an object file
src/ConflictRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ConflictRepository.cpp.o
.PHONY : src/ConflictRepository.cpp.o

src/ConflictRepository.i: src/ConflictRepository.cpp.i
.PHONY : src/ConflictRepository.i

# target to preprocess a source file
src/ConflictRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ConflictRepository.cpp.i
.PHONY : src/ConflictRepository.cpp.i

src/ConflictRepository.s: src/ConflictRepository.cpp.s
.PHONY : src/ConflictRepository.s

# target to generate assembly for a file
src/ConflictRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ConflictRepository.cpp.s
.PHONY : src/ConflictRepository.cpp.s

src/DatabaseManager.o: src/DatabaseManager.cpp.o
.PHONY : src/DatabaseManager.o

# target to build an object file
src/DatabaseManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/DatabaseManager.cpp.o
.PHONY : src/DatabaseManager.cpp.o

src/DatabaseManager.i: src/DatabaseManager.cpp.i
.PHONY : src/DatabaseManager.i

# target to preprocess a source file
src/DatabaseManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/DatabaseManager.cpp.i
.PHONY : src/DatabaseManager.cpp.i

src/DatabaseManager.s: src/DatabaseManager.cpp.s
.PHONY : src/DatabaseManager.s

# target to generate assembly for a file
src/DatabaseManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/DatabaseManager.cpp.s
.PHONY : src/DatabaseManager.cpp.s

src/FlightProcedure.o: src/FlightProcedure.cpp.o
.PHONY : src/FlightProcedure.o

# target to build an object file
src/FlightProcedure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedure.cpp.o
.PHONY : src/FlightProcedure.cpp.o

src/FlightProcedure.i: src/FlightProcedure.cpp.i
.PHONY : src/FlightProcedure.i

# target to preprocess a source file
src/FlightProcedure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedure.cpp.i
.PHONY : src/FlightProcedure.cpp.i

src/FlightProcedure.s: src/FlightProcedure.cpp.s
.PHONY : src/FlightProcedure.s

# target to generate assembly for a file
src/FlightProcedure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedure.cpp.s
.PHONY : src/FlightProcedure.cpp.s

src/FlightProcedureController.o: src/FlightProcedureController.cpp.o
.PHONY : src/FlightProcedureController.o

# target to build an object file
src/FlightProcedureController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedureController.cpp.o
.PHONY : src/FlightProcedureController.cpp.o

src/FlightProcedureController.i: src/FlightProcedureController.cpp.i
.PHONY : src/FlightProcedureController.i

# target to preprocess a source file
src/FlightProcedureController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedureController.cpp.i
.PHONY : src/FlightProcedureController.cpp.i

src/FlightProcedureController.s: src/FlightProcedureController.cpp.s
.PHONY : src/FlightProcedureController.s

# target to generate assembly for a file
src/FlightProcedureController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedureController.cpp.s
.PHONY : src/FlightProcedureController.cpp.s

src/FlightProcedureRepository.o: src/FlightProcedureRepository.cpp.o
.PHONY : src/FlightProcedureRepository.o

# target to build an object file
src/FlightProcedureRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedureRepository.cpp.o
.PHONY : src/FlightProcedureRepository.cpp.o

src/FlightProcedureRepository.i: src/FlightProcedureRepository.cpp.i
.PHONY : src/FlightProcedureRepository.i

# target to preprocess a source file
src/FlightProcedureRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedureRepository.cpp.i
.PHONY : src/FlightProcedureRepository.cpp.i

src/FlightProcedureRepository.s: src/FlightProcedureRepository.cpp.s
.PHONY : src/FlightProcedureRepository.s

# target to generate assembly for a file
src/FlightProcedureRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/FlightProcedureRepository.cpp.s
.PHONY : src/FlightProcedureRepository.cpp.s

src/Project.o: src/Project.cpp.o
.PHONY : src/Project.o

# target to build an object file
src/Project.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/Project.cpp.o
.PHONY : src/Project.cpp.o

src/Project.i: src/Project.cpp.i
.PHONY : src/Project.i

# target to preprocess a source file
src/Project.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/Project.cpp.i
.PHONY : src/Project.cpp.i

src/Project.s: src/Project.cpp.s
.PHONY : src/Project.s

# target to generate assembly for a file
src/Project.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/Project.cpp.s
.PHONY : src/Project.cpp.s

src/ProjectController.o: src/ProjectController.cpp.o
.PHONY : src/ProjectController.o

# target to build an object file
src/ProjectController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ProjectController.cpp.o
.PHONY : src/ProjectController.cpp.o

src/ProjectController.i: src/ProjectController.cpp.i
.PHONY : src/ProjectController.i

# target to preprocess a source file
src/ProjectController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ProjectController.cpp.i
.PHONY : src/ProjectController.cpp.i

src/ProjectController.s: src/ProjectController.cpp.s
.PHONY : src/ProjectController.s

# target to generate assembly for a file
src/ProjectController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ProjectController.cpp.s
.PHONY : src/ProjectController.cpp.s

src/ProjectRepository.o: src/ProjectRepository.cpp.o
.PHONY : src/ProjectRepository.o

# target to build an object file
src/ProjectRepository.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ProjectRepository.cpp.o
.PHONY : src/ProjectRepository.cpp.o

src/ProjectRepository.i: src/ProjectRepository.cpp.i
.PHONY : src/ProjectRepository.i

# target to preprocess a source file
src/ProjectRepository.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ProjectRepository.cpp.i
.PHONY : src/ProjectRepository.cpp.i

src/ProjectRepository.s: src/ProjectRepository.cpp.s
.PHONY : src/ProjectRepository.s

# target to generate assembly for a file
src/ProjectRepository.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/ProjectRepository.cpp.s
.PHONY : src/ProjectRepository.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aeronautical_backend.dir/build.make CMakeFiles/aeronautical_backend.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... aeronautical_backend"
	@echo "... src/ConflictController.o"
	@echo "... src/ConflictController.i"
	@echo "... src/ConflictController.s"
	@echo "... src/ConflictRepository.o"
	@echo "... src/ConflictRepository.i"
	@echo "... src/ConflictRepository.s"
	@echo "... src/DatabaseManager.o"
	@echo "... src/DatabaseManager.i"
	@echo "... src/DatabaseManager.s"
	@echo "... src/FlightProcedure.o"
	@echo "... src/FlightProcedure.i"
	@echo "... src/FlightProcedure.s"
	@echo "... src/FlightProcedureController.o"
	@echo "... src/FlightProcedureController.i"
	@echo "... src/FlightProcedureController.s"
	@echo "... src/FlightProcedureRepository.o"
	@echo "... src/FlightProcedureRepository.i"
	@echo "... src/FlightProcedureRepository.s"
	@echo "... src/Project.o"
	@echo "... src/Project.i"
	@echo "... src/Project.s"
	@echo "... src/ProjectController.o"
	@echo "... src/ProjectController.i"
	@echo "... src/ProjectController.s"
	@echo "... src/ProjectRepository.o"
	@echo "... src/ProjectRepository.i"
	@echo "... src/ProjectRepository.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

